// Load required packages
var mongoose = require('mongoose');
// Define our AccountingService schema

var Schema = new mongoose.Schema({
     _id      :{ type: String }, 
     createdAt      :{ type: Date }, 
     updatedAt      :{ type: Date }, 
     priceRange      :{ type: String }, 
     paymentAccepted      :{ type: String }, 
     openingHours      :{ type: String }, 
     currenciesAccepted      :{ type: String }, 
     branchOf      :{ type: String }, 
     vatID      :{ type: String }, 
     taxID      :{ type: String }, 
     subOrganization      :{ type: String }, 
     seeks      :{ type: String }, 
     owns      :{ type: String }, 
     naics      :{ type: String }, 
     members      :{ type: String }, 
     member      :{ type: String }, 
     makesOffer      :{ type: String }, 
     location      :{ type: Object }, 
     legalName      :{ type: String }, 
     hasPOS      :{ type: String }, 
     foundingDate      :{ type: String }, 
     founders      :{ type: String }, 
     founder      :{ type: String }, 
     employees      :{ type: String }, 
     employee      :{ type: String }, 
     email      :{ type: String }, 
     duns      :{ type: String }, 
     department      :{ type: String }, 
     contactPoints      :{ type: String }, 
     contactPoint      :{ type: String }, 
     brand      :{ type: String }, 
     telephone      :{ type: String }, 
     reviews      :{ type: String }, 
     review      :{ type: String }, 
     photos      :{ type: String }, 
     photo      :{ type: String }, 
     openingHoursSpecification      :{ type: String }, 
     maps      :{ type: String }, 
     map      :{ type: String }, 
     logo      :{ type: String }, 
     isicV4      :{ type: String }, 
     interactionCount      :{ type: String }, 
     globalLocationNumber      :{ type: String }, 
     geo      :{ type: String }, 
     faxNumber      :{ type: String }, 
     events      :{ type: String }, 
     event      :{ type: String }, 
     containedIn      :{ type: String }, 
     aggregateRating      :{ type: String }, 
     address      :{ type: String }, 
     url      :{ type: String }, 
     name      :{ type: String }, 
     image      :{ type: String }, 
     description      :{ type: String }, 
});

// Export the Mongoose model
module.exports = mongoose.model('AccountingService', Schema);