// Load required packages
var mongoose = require('mongoose');
// Define our Person schema

var Schema = new mongoose.Schema({
     _id      :{ type: String }, 
     createdAt      :{ type: Date }, 
     updatedAt      :{ type: Date }, 
     worksFor      :{ type: String }, 
     workLocation      :{ type: String }, 
     vatID      :{ type: String }, 
     telephone      :{ type: String }, 
     taxID      :{ type: String }, 
     spouse      :{ type: String }, 
     siblings      :{ type: String }, 
     sibling      :{ type: String }, 
     seeks      :{ type: String }, 
     relatedTo      :{ type: String }, 
     performerIn      :{ type: String }, 
     parents      :{ type: String }, 
     parent      :{ type: String }, 
     owns      :{ type: String }, 
     nationality      :{ type: String }, 
     naics      :{ type: String }, 
     memberOf      :{ type: String }, 
     makesOffer      :{ type: String }, 
     knows      :{ type: String }, 
     jobTitle      :{ type: String }, 
     isicV4      :{ type: String }, 
     interactionCount      :{ type: String }, 
     honorificSuffix      :{ type: String }, 
     honorificPrefix      :{ type: String }, 
     homeLocation      :{ type: String }, 
     hasPOS      :{ type: String }, 
     globalLocationNumber      :{ type: String }, 
     givenName      :{ type: String }, 
     gender      :{ type: String }, 
     follows      :{ type: String }, 
     faxNumber      :{ type: String }, 
     familyName      :{ type: String }, 
     email      :{ type: String }, 
     duns      :{ type: String }, 
     deathDate      :{ type: String }, 
     contactPoints      :{ type: String }, 
     contactPoint      :{ type: String }, 
     colleagues      :{ type: String }, 
     colleague      :{ type: String }, 
     children      :{ type: String }, 
     brand      :{ type: String }, 
     birthDate      :{ type: String }, 
     awards      :{ type: String }, 
     award      :{ type: String }, 
     alumniOf      :{ type: String }, 
     affiliation      :{ type: String }, 
     address      :{ type: String }, 
     additionalName      :{ type: String }, 
     url      :{ type: String }, 
     name      :{ type: String }, 
     image      :{ type: String }, 
     description      :{ type: String }, 
});

// Export the Mongoose model
module.exports = mongoose.model('Person', Schema);